### ISSUE TITLE
Mention "deck of playing cards" in docs

### ISSUE THREAD

**Issue by NNemec** [Luapulu/Shuffle.jl#1]
Though the code could be used to shuffle arbitrary items, the algorithms are inspired by physically shuffling playing cards. This should be mentioned early on to guide the reader.

**Comment by Luapulu** [comment]
Yes, I'll add short descriptions for `Faro` / `Weave` and `GilbertShannonReeds`. The docs already have links to wikipedia but a short description would be useful.

**Comment by Luapulu** [comment]
Card shuffling mentioned in https://luapulu.github.io/Shuffle.jl/dev/reference/#Shuffle.GilbertShannonReeds

**Comment by Luapulu** [comment]
Card shuffling also mentioned in https://luapulu.github.io/Shuffle.jl/dev/reference/#Shuffle.Faro
