### ISSUE TITLE
Interface to uniform shuffle algorithm

### ISSUE THREAD

**Issue by NNemec** [Luapulu/Shuffle.jl#2]
For easy drop-in comparison, 
I would expect an algorithm providing a uniform shuffle through the same Interface.

**Comment by Luapulu** [comment]
Depending on what you mean by uniform shuffle, this is already implemented. If by uniform, you mean perfectly random, then
`shuffle(arr, FisherYates())`, does that. In fact, `FisherYates` is set to the default so you can even just do `shuffle(arr)` to shuffle perfectly randomly.

I'll see if I can make that clearer in the docs.

**Comment by Luapulu** [comment]
The newest [docs](https://luapulu.github.io/Shuffle.jl/dev) have a basic usage section that makes it fairly clear.

**Comment by NNemec** [comment]
As I understand, FisherYates is not a model for a shuffle, but an algorithm to achieve for a perfectly random shuffle, right? In that case, it should not be named in the API but kept as an implementation detail. An API should only specify what the code does, not how it does that, otherwise you are unnecessarily limiting yourself from improving the implementation. (If you consider acknowledging the source of the algorithm important, you may want to add it as non-binding comment to the API docs.)

**Comment by Luapulu** [comment]
Ah, I see. Yes, good point. I'll rename it to RandShuffle or something like that. I should also deemphasize that the default shuffle behaves in the same way as `Random.shuffle`. If I ever implement the algorithm differently to the standard library's `Random` module, they may no longer behave identically.

**Comment by Luapulu** [comment]
`FisherYates` has been renamed to `RandomShuffle`. It is no longer part of the public API, that Fisher-Yates is used to achieve a random shuffle.
